#- defaults:
#    name: global
#    arch: 'i386'

- project:
    name: build-test
    jobs:
        - 'build-test'

- job-template:
    name: 'build-test'
    project-type: pipeline
    sandbox: true
    pipeline-scm:
      scm:
        - git:
            url: http://git-cache.dev.whirl.sg:9909/bitbucket.org/whirlsoftware/whirl_devops
            credentials-id: '87657576578657685'
            branches:
              -  'devops_branch'
      script-path: '{arch}'




## jenkins-jobs --conf ../../jenkins-builder.ini update project.yaml:defaults.yml