apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "elastic-mapping.fullname" . }}
  labels:
    app: {{ include "elastic-mapping.name" . }}
    chart: {{ include "elastic-mapping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
         containers:
           - name: elastic-mapping-update
             image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
             volumeMounts:
               - name: workdir
                 mountPath: "/workdir"
                 readOnly: false
             env:
               - name: ELASTICSEARCH_URL
                 value: "{{ .Values.ELASTICSEARCH_URL }}"
             command: ["./workdir/run.sh"]
         volumes:
           - name: workdir
             configMap:
                name: "{{ include "elastic-mapping.fullname" . }}"
         restartPolicy: Never
