apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "elastic-mapping.fullname" . }}
  labels:
    app: {{ include "elastic-mapping.name" . }}
    chart: {{ include "elastic-mapping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
    backoffLimit: 2
    template:
       metadata:
         labels:
            app: {{ include "elastic-mapping.name" . }}
            chart: {{ include "elastic-mapping.chart" . }}
            release: {{ .Release.Name }}
            heritage: {{ .Release.Service }}
       spec:
         containers:
           - name: elastic-mapping-update
             image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
             volumeMounts:
               - name: workdir
                 mountPath: "/workdir"
                 readOnly: false
             env:
               - name: ELASTICSEARCH_URL
                 value: "{{ .Values.ELASTICSEARCH_URL }}"
               - name: MAPPING_LIST
                 value: "{{ .Values.MAPPING_LIST }}"
               - name: MAPPING_ACTION
                 value: "{{ .Values.MAPPING_ACTION }}"
             command: ["/workdir/run.sh"] 
         volumes:
           - name: workdir
             configMap:
                name: "{{ include "elastic-mapping.fullname" . }}"
                defaultMode: 0744
         restartPolicy: Never
